name: Deploy test-Deploy
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PWD }}
          script_stop: true
          script: |
            # ls -al
            # touch test.txt
            # echo "hello imooc" >> test.txt
            # cat test.txt

            cd /root/resource/nginx/
            ls -al
            rm -rf vue3-test-deploy
            git clone git@github.com:ziyi-joiede/vue3-test-deploy.git -b ${{github.ref_name}}
            cd vue3-test-deploy
            npm install
            npm run build
